- README.md
- requirements.txt
Hi @rustyrussell,
Before all, this PR maybe is totally wrong and I have some error inside my things, if it is wrong, I so sorry.
I try to run the first time lnprototest and I noted from the command `pip install -r requirements.txt` I have some error, such as:
- == and not = inside the bitcoin lib dependence. (thanks pip to suggest this change :smile: )
- dependence not found, during the process of installation, so at this point I jumped inside the [lnpy online repo](https://pypi.org/search/?q=pyln) and I reported the dependence inside it
The most common error inside the `pip install` process is the following
```
ERROR: pyln-bolt7 1.0.1.137 has requirement pyln.proto==0.8.4, but you'll have pyln-proto 0.8.3 which is incompatible.
ERROR: pyln-bolt4 1.0.1.137 has requirement …
```
> first run: update requirements.txt and update README.md

- lnprototest/__init__.py
- lnprototest/event.py
- requirements.txt
- tests/test_bolt7-20-query_channel_range.py
Still have some problems locally with `pyln.testing` wanting `python-bitcoinlib` of version 0.10.2. We should have a new pypi update of `pyln-testing` after the release though, which should allow us to peg the requirement to `pyln-testing==0.10.0` and hopefully fix this once and for all.
> Small Edits

- lnprototest/backend/__init__.py
- lnprototest/backend/backend.py
- lnprototest/backend/bitcoind.py
- lnprototest/clightning/clightning.py
This PR make a ~~draft~~ implementation of the discussion that we had in #11 with @niftynei and @t-bast.
I used the abstract concept of python that required to implementation of the abstract method, but I'm not sure that is a good thing to do here.
~~I open this in the draft because the code is not well-formatted, but~~ I would like to have some feedback also from @rustyrussell to know if this can be an improvement of the framework or a not useful refactoring.
> Generalizzation of Bitcoin backend concept and safe support of Bitcoin Core 0.21.*

- requirements.txt
- tests/test_bolt7-20-query_channel_range.py
Remove the warning message in the c-lightning test about the crc32c dependence
> Removed deprecated crc32c API and fix the version crc32c into requirements.txt

- lnprototest/clightning/clightning.py
- lnprototest/event.py
- lnprototest/proposals.py
- tests/test_bolt2-20-open_channel_accepter.py
You gotta make your feerate at least 65/64ths of the previous though
> dual-funding: update init_rbf, replacing 'fee_step' with explicit fee

- lnprototest/clightning/clightning.py
clightning's default is going to switch to "true", so we explicitly set it to false for these tests.
> clightning: explicitly set 'leases-only' to false

- HACKING.md
- lnprototest/backend/bitcoind.py
This is causing a CI flake, because our "do we really need to restart?" logic is wrong.  @vincenzopalazzo changed the block number when he extracted the backend (which was wrong), but the test for mempool was always backwards!
And updated documentation, too.
> Fix restart flake

- lnprototest/__init__.py
- lnprototest/backend/bitcoind.py
- lnprototest/clightning/clightning.py
- lnprototest/utils.py
- requirements.txt
As mentioned correctly in issue #17 the pyln.testing require the postgress dependencies, but inside the lnprototest there are no any reason to use the package pyln.testing, because is used only util functions. With this commit, I removed the dependencies, and I reproduce the few lines of code that are imported from the pyln package.
Change-log: Remove pyln.testing to remove the dependencies problem with pip
> Update dependence and remove pyln.testing dependences

- lnprototest/clightning/clightning.py
Mac OS X limits rpc full paths to 104 characters. Using mkdtemp results in a path that is too long.
On Mac OS X 11.4, Xcode 12.5.1 (12E507), the rpc file was placed at:
/var/folders/6k/gjk2k1wn6yb38kx5480jdhdh0000gn/T/lnprototest-clightning-p_xswkz9/lightningd/regtest/lightning-rpc
which is 113 characters (9 too long).
Shortening the prefix gets us below the limit.
> Generated temporary path too long for Mac OS X

- lnprototest/structure.py
ignored_by_all does not return a bool, it returns None (don't ignore),
[] (ignore), or [msg] (ignore, but send this reply).
Cut & paste the handling from OneOf to fix this error:
```
E           lnprototest.errors.EventError: (AnyOrder:test_bolt7-10-gossip-filter.py:147, 'Message did not match any sequences [ExpectMsg:test_bolt7-10-gossip-filter.py:149]: gossip_timestamp_filter chain_hash=06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f first_timestamp=1648092671 timestamp_range=4294967295')
```
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
> AnyOrder: fix ignored message handling.

- lnprototest/backend/bitcoind.py
Due the refactoring the following code was introduced
```
def __is__bitcoind_ready(self) -> bool:
"""Check if bitcoind is ready during the execution"""
if self.rpc is None:
raise ValueError("bitcoind not initialized")
try:
self.btc_version = self.rpc.getnetworkinfo()
return True
except Exception as ex:
logging.debug(f"{ex}")
return False
```
That it is not smarter for a language low by default like python.
using instead the Rusty version, much better 
```
def __is__bitcoind_ready(self) -> bool:
"""Check if bitcoind is ready during the execution"""
if self.proc is None:
raise ValueError("bitcoind not initialized")
while b"Done loading" not in self.proc.stdout.readline():
pass
return True
```
> lnprototest: improve the code is the bitcoin core is running

- tests/conftest.py
The scope session can cause problems when two tests are running in parallel, because if the lnprototest is not new, it is possible that we are sharing the process.
Changelog-Fixed: Fix the fixture scope of the runner.
> tests: slow down the fixtures scope from session to scope

- lnprototest/clightning/clightning.py
Ran into a bug where clightning exits before bitcoind is ready for an rpc connection. 
Bitcoind.start() already confirms rpc connection before returning, which can be
taken advantage of be calling the bitcoind and clightning in order.
```
--------------- Captured stderr call ------------------
Could not connect to bitcoind using bitcoin-cli. Is bitcoind running?
Make sure you have bitcoind running and that bitcoin-cli is able to connect to bitcoind.
You can verify that your Bitcoin Core installation is ready for use by running:
$ bitcoin-cli -regtest -rpcport=39071 -rpcuser=... -rpcpassword=... echo 'hello world'
The Bitcoin backend died.
DEBUG:lnprototest.runner:RUN Bitcoind
DEBUG:lnprototest.runner:RUN c-lightning
```
> clightning Runner: start bitcoind before clightning

- lnprototest/__init__.py
- lnprototest/clightning/clightning.py
- lnprototest/event.py
- lnprototest/runner.py
- lnprototest/structure.py
- poetry.lock
- pyproject.toml
- tests/helpers.py
- tests/spec_helper.py
- tests/test_bolt7-01-channel_announcement-success.py
- tests/test_bolt7-10-gossip-filter.py
This PR introduces some code improvements related to lnprototest, in particular now:
- lnprototest is able to print the log to the console in case of failure, and make a backup of the log file in the `/tmp` dir;
- introduce some utils function in the tests dir related to:
- test utils, included a function to manage the runner and some others function useful to build the tests. This also introduces a bug fixing to stop the runner when a test by lnprototest fails;
- spec utils, include a collection of functions to build a well-formed sequence of events to make lightning operations, like connecting to a node or opening a channel. The last change gives the possibility to write tests a smaller
> lnprototest: API improvement and introduction of test utils function

- docker/entrypoint.sh
- lnprototest/backend/backend.py
- lnprototest/backend/bitcoind.py
- lnprototest/clightning/clightning.py
- lnprototest/funding.py
- poetry.lock
- tests/test_bolt2-20-open_channel_accepter.py
This is a different approach from #52 which use the idea to move the reserve port call in the start method, but doesn't hack the bitcoind stop method, but instead when the stop is called the bitcoin core is stopped and killed.
The main reason is that the stop method is a core method of lnprototest to clean up the env, and it is called only when a test is failed to avoid keeping zombies bitcoind alive
Adding also a couple of improvements to avoid merging a buggy PR, now the integration test are run 10 times, and if one fails, the tests fail!
Fixes https://github.com/rustyrussell/lnprototest/issues/31 by @niftynei in https://github.com/ElementsProject/lightning/pull/5367
> bitcoind: make sure that the reserve port is really free!

- .github/workflows/build.yml
- Makefile
- docker/Dockerfile.clightning
- docker/entrypoint.sh
- lnprototest/backend/bitcoind.py
- lnprototest/clightning/clightning.py
- lnprototest/commit_tx.py
- lnprototest/funding.py
- lnprototest/runner.py
- poetry.lock
- pyproject.toml
- tests/spec_helper.py
- tests/test_bolt2-01-open_channel.py
- tests/test_bolt2-02-reestablish.py
- tests/test_bolt2-10-add-htlc.py
- tests/test_bolt2-20-open_channel_accepter.py
- tests/test_bolt7-01-channel_announcement-success.py
- tests/test_bolt7-02-channel_announcement-failure.py
- tests/test_bolt7-10-gossip-filter.py
- tests/test_bolt7-20-query_channel_range.py
OpenSSL removed ripemd160, which impacts the default impl of hashlib for most python installs (true as of 22.04 LTS).
While we're here, let's update to the newest libs for everything, which requires also updating some of the tests.
See also:
- openssl/openssl#16994
- bitcoin/bitcoin#23710
- petertodd/python-bitcoinlib#277
> openssl: add fallback for ripemd160 implementation

- tests/test_bolt7-01-channel_announcement-success.py
Fixes https://github.com/rustyrussell/lnprototest/issues/60
Implementation proposal: https://github.com/lightning/bolts/pull/1004
Changelog-Added: gossip: delay considering a channel edge deleted for 12-blocks proposed by https://github.com/lightning/bolts/pull/1004
> bolt7: delay considering a channel edge deleted for 12-blocks

- .flake8
- .github/workflows/testing.yml
- docker/Dockerfile.clightning
- docker/entrypoint.sh
- lnprototest/__init__.py
- lnprototest/event.py
- lnprototest/structure.py
- lnprototest/utils/__init__.py
- lnprototest/utils/bitcoin_utils.py
- lnprototest/utils/ln_spec_utils.py
- lnprototest/utils/utils.py
- poetry.lock
- tests/spec_helper.py
- tests/test_bolt2-01-close_channel.py
This is one of my first attempts to implement the interoperability test for the shutdown workflow described in [BOLT2](https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#channel-close)
This should clarify the idea on the implementation side about the following discussion https://github.com/lightning/bolts/issues/964 and https://github.com/lightning/bolts/pull/970
> bolt2: add coop close test 

- lnprototest/clightning/clightning.py
I was having some difficulty running lnprototest locally because it was reading my `bitcoin.conf` which points to a remote `bitcoind` that doesn't have `regtest` running. This caused tests to hang and time out since it couldn't connect to `bitcoind`. This now specifies that we want to connect to the local regtest node we just spun up.
> cln: Use full hostname:port `rpcconnect` instead of just `rpcport`

- tests/test_bolt2-20-open_channel_accepter.py
This will help to see the cln log in more tests if something fails
> feat: use the run_runner helper in more tests

- lnprototest/clightning/clightning.py
- lnprototest/event.py
- tests/test_bolt2-01-close_channel.py
- tests/test_bolt2-01-open_channel.py
when we send a message from cln to the runner we should be in an async mode, and this
is implemented with a thread pool. 
Now, when there are multiple failures (exception at the same time) the 
python runtime mess up all the stack trace and this makes the debugging
of cln log is no longer possible in the console.
So this try to fix this problem
> fix: cleanup funding code and avoid raise multiple exceptions

- HACKING.md
- README.md
- lnprototest/backend/bitcoind.py
- lnprototest/clightning/__init__.py
- lnprototest/clightning/clightning.py
- tests/test_bolt2-01-open_channel.py
- tests/test_bolt2-20-open_channel_accepter.py
- tests/test_bolt2-30-channel_type-open-accept-tlvs.py
- tests/test_bolt7-20-query_channel_range.py
This is an update in the code comments to match name change for the Lightning implementation from c-lightning to core-lightning. I referred to this [article](https://blog.blockstream.com/en-c-lightning-is-now-core-lightning/)
> Update documentation c-lightning references to core-lightning

- lnprototest/clightning/clightning.py
- tests/test_bolt2-01-open_channel.py
There is some case where lnprototest send the message too fast, well lnprototest is always too fast but in most case, we simulate the `time.sleep` inside the ExpectedMsg that iterates for a while till the message is not received.
This is no longer true if lnprototest sends a message and the next steps is not the ExpectedMsg or equal but a message that required that the message sent to lnprototest is already processed, like in the `FundChannel(...)` case.
So this PR is introducing a new Event `Wait` that will allow us to wait some time before processing the next message 
Fixes https://github.com/rustyrussell/lnprototest/issues/74
> fix: add Wait event to allow to slow down lnptototest

- changelog.json
- pyproject.toml
This uses a changelog extractor available here https://github.com/vincenzopalazzo/changelog.dart which for now works with the Github API.
But it is fine for now, I do not want use the extra script!
With this, we are tagging the version v0.0.2 of lnprototest
> docs: configure the changelog for the next release

- tests/test_bolt2-30-channel_type-open-accept-tlvs.py
Channel types does not require anchors!
This is needed for https://github.com/ElementsProject/lightning/pull/6209
> tests/test_bolt2-30-channel_type-open-accept-tlvs.py: remove compulsory feature

- lnprototest/stash/stash.py
- lnprototest/utils/ln_spec_utils.py
- tests/test_bolt2-01-open_channel.py
This commit improves the method for generating the sequence of events needed to connect to a node from the sender side.
Specifically, we can now retrieve the same feature that the node sends to the runner.
This is useful because if the features do not match, the connection must be closed.
> fix: Grab the feature from the init message if it is not specified

- lnprototest/utils/ln_spec_utils.py
Signature exchanges are signed with the node's private key and verified by the counterpart using the node's ID (which is the public key). The signatures should not be the same because the lightning implementation and lnprototest do not have the same private key, or better yet, lnprototest will fake a different private key.
Unfortunately, we lack the tools to easily create this signature, making lnprototest a painful process. Apologies for the inconvenience!
Therefore, we should have a tool to calculate the signatures at some point. But for now, we are leveraging the lightning specification and skipping the announce signature message.
This significantly simplifies the workflow.
> feat: Open channel helper ignores announcement signatures

- lnprototest/runner.py
- lnprototest/utils/ln_spec_utils.py
- tests/test_bolt2-01-close_channel.py
- tests/test_bolt2-01-open_channel.py
A function `runner_features` is added as an abstract method to the runner class. This methods provides the features required by an implementation to Lnprototest. This makes Lnprototest compatible with other implementations. 
The tests are also modified to use this function in `connect_to_node_helper`.
> fix: runner_features added in runner.py and tests modified

- lnprototest/event.py
- tests/test_bolt7-02-channel_announcement-failure.py
This commit addresses an issue with the error checking mechanism. Currently, the `ExpectError` function only verifies the occurrence of an error during the connection, without considering the specific error message expected.
The upcoming changes in [1] will simplify lnprototest, but until then, this fix provides a straightforward and effective solution for checking error messages.
[1] https://github.com/rustyrussell/lnprototest/pull/95
> fix: Correct error check for expected errors

- tests/test_bolt2-01-open_channel.py
Fixes a bug in lnprototest by removing the problematic code outlined in patch [1].
During our investigation of the cln code, we discovered that the message verification was not performed correctly as the BOL 7 suggest. This commit includes a patch [2] that fixes the issue and introduces an integration test to validate that core lightning adheres to the signature verification guidelines outlined in BOLT7.
[1] https://github.com/rustyrussell/lnprototest/pull/91
[2] https://github.com/ElementsProject/lightning/pull/6384
Reported-by: lnprototest (https://github.com/rustyrussell/lnprototest/pull/91)
P.S: now the integration testing should fails because the patch in core lightning is still open
> feat(test): Add a new test to ensure proper signature checking

- lnprototest/backend/bitcoind.py
- lnprototest/keyset.py
- pyproject.toml
- tests/test_bolt1-01-init.py
A few years ago, I added this code for compatibility with Bitcoin Core 21.
Now that I am integrating it with the LDK node runner, and LDK can use a wallet to set up a node with Bitcoin Core, we need a way to disable the wallet from Bitcoin Core to keep our integration simpler.
Without this change, Bitcoin Core would have two wallets, and we would need to set up the correct wallet in our architecture.
However, we can simply disable it to avoid this issue.
Fixes https://github.com/rustyrussell/lnprototest/issues/102
> feat: Allowing the option to skip the creation of the wallet in bitcoind

- lnprototest/clightning/clightning.py
This is being added instead of the build-time setting for v23.11.
> cln: specify --developer if supported.

- docker/Dockerfile.clightning
- lnprototest/event.py
- lnprototest/utils/ln_spec_utils.py
- tests/test_bolt2-01-open_channel.py
Previously, an unexpected behavior in the ln helper function had gone
unnoticed. However, while Rusty Russell was working on [1], he
discovered a bug in lnprototest.
Specifically, within the helper function that opens a channel, there
was an incorrect way of counting the current block height. Ideally,
this logic should be abstracted elsewhere.
This commit addresses the block height counting
error and resolves the bug identified in [1].
[1] https://github.com/ElementsProject/lightning/pull/6628
Link: https://discord.com/channels/899980449231814676/941465665540325397/1154259454716563537
Reported-by: Rusty Russell <rusty@rustcorp.com.au>
> fix: Correct reorg issue in the ln helper function

- lnprototest/clightning/clightning.py
The mystery of why pythons do not fail sometimes
is still open to me, but anyway.
This commit is fixing the check on the exit code,
because the subprocess.run will not return
an exit code when the error happens in the command line.
But it will throw an exception, see this example below
```
>>> subprocess.run(["l", "-pp"])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.11/subprocess.py", line 548, in run
with Popen(*popenargs, **kwargs) as process:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename) …
```
> cln: fix the check on the exit code

- tests/test_bolt2-30-channel_type-open-accept-tlvs.py
Modern CLN will reject this, now it requires static remotekey.
> tests/test_bolt2-30-channel_type-open-accept-tlvs.py: don't test empty channel type.

- tests/test_bolt1-01-init.py
- tests/test_bolt1-02-unknown-messages.py
The usage of the TryAll is very usefull when we are doing specify test (e.g: testing different kind of feature bits) support.
However, it is over complex where the test is doing other thing to use the `TryAll`.
So this is removing some `TryAll` in some init tests.
Suggested-by: @rustyrussell
> tests: semplify the init tests

- docker/Dockerfile.clightning
cln version 24.05 is the last version of core lightning that it is
working with the version of prototest. Most lickly this is a cln
bug described in the following issue [1].
However, we pin the cln version and report the bug to mainline probably
someone will be able to find the real issue in the cln or lnprototest
at some point.
[1] https://github.com/rustyrussell/lnprototest/issues/123
> meta: fix cln version to 24.05 

- tests/test_bolt1-01-init.py
- tests/test_bolt1-02-unknown-messages.py
- tests/test_bolt2-10-add-htlc.py
- tests/test_bolt2-30-channel_type-open-accept-tlvs.py
- tests/test_bolt7-01-channel_announcement-success.py
- tests/test_bolt7-02-channel_announcement-failure.py
- tests/test_bolt7-10-gossip-filter.py
- tests/test_bolt7-20-query_channel_range.py
Tests are updated to use `runner_features` and `stash_field_from_event`, this allows the tests to support multiple lightning implementations at the same time.
> fix: using runner_features and stash_field_from_event inside tests

- .github/workflows/build.yml
- .github/workflows/testing.yml
- docker/Dockerfile.ldk
- docker/docker-compose.yml
- docker/ldk-entrypoint.sh
This commit adds a workflow for integrating LDK-Sample with Lnprototest. A dockerfile is also added to build LDK-Sample and run Lnprototest against it.
> LDK workflow and dockerfile added

- tests/test_bolt1-02-unknown-messages.py
- tests/test_bolt2-01-open_channel.py
Some implementations send an error message and, at the same time, will close the connection. Locally, this will cause a reading from a closed socket.
However, ldk now has a different life cycle for the connection, and we should receive the error message before.
```
lnprototest.errors.EventError: `Peer did not disconnect` on event [{"event": "ExpectDisconnect", "file": "test_bolt2-01-open_channel.py", "pos": "345"},]
=========================== short test summary info ============================
FAILED ../lnprototest/tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side_wrong_announcement_signatures
============= 1 failed, 29 passed, 17 skipped in 96.15s (0:01:36) ==============
```
Fixes https://github.com/rustyrussell/lnprototest/issues/134
Reported-by: @Psycho-Pirate
> tests: include the test for the tests
